spring.application.name=main-service

# === Server ===
server.port=${SERVER_PORT:8080}

# === Database configuration ===
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewm-main}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:dbuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345}

# === JPA settings ===
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# === SQL initialization ===
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# === JSON formatting ===
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Europe/Moscow
spring.jackson.serialization.write-dates-as-timestamps=false

# === Actuator ===
management.endpoints.web.exposure.include=health,info,metrics,mappings
management.endpoint.health.show-details=always

# === Stats Client ===
stats-server.url=${STATS_SERVER_URL:http://localhost:9090}

# === Logging ===
logging.level.root=INFO
logging.level.ru.practicum=DEBUG

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
